### ISSUE TITLE
Fails to build on 32-bit FreeBSD

### ISSUE THREAD

**Issue by jbeich** [zmwangx/rust-ffmpeg-sys#96]
Regressed by #89

```rust
$ git describe --tags
7.0.3-1-ga13516c

$ rustc -vV
rustc 1.82.0 (f6e511eec 2024-10-15) (built from a source tarball)
binary: rustc
commit-hash: f6e511eec7342f59a25f7c0534f1dbea00d01b14
commit-date: 2024-10-15
host: i686-unknown-freebsd
release: 1.82.0
LLVM version: 19.1.1

$ pkg info -x ffmpeg
ffmpeg-6.1.2_5,1
$ pkg-config --modversion libavcodec
60.31.102

$ cargo build
[...]
error[E0080]: evaluation of constant value failed
    --> ./target/debug/build/ffmpeg-sys-next-a158c93c9f2c6912/out/bindings.rs:1442:31
     |
1442 |     ["Size of __max_align_t"][::std::mem::size_of::<__max_align_t>() - 20usize];
     |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ attempt to compute `16_usize - 20_usize`, which would overflow

For more information about this error, try `rustc --explain E0080`.
```
